1.13.4 Moar creator validation
tensor-hq/tensor-common pull request #4
Opened 2023-06-01 20:59 UTC by avoc-ado

2023-06-01 23:07 UTC, richardwu requested changes

2023-06-01 23:07 UTC, richardwu commented on src/creator/validation.ts
> +  'UTILITIES',
What about "UTILITY"?

2023-06-01 23:32 UTC, avoc-ado commented on src/creator/validation.ts
> +  'UTILITIES',
Yeah it can be utility

2023-06-01 23:47 UTC, avoc-ado commented on src/creator/validation.ts
> +  'UTILITIES',
Done

2023-06-02 00:06 UTC, richardwu approved these changes

2023-06-02 00:06 UTC, merged